.TH geni-list-idp-members 1 "July 10, 2015"
.SH NAME
geni-list-idp-members \- list the identity providers and a count of their
users
.SH SYNOPSIS
.B geni-list-idp-members
[\-c CONFIG]
.SH DESCRIPTION
List all identity providers know to the GENI member authority and a count
indicating how many members come from each.
.SH OPTIONS
.TP
\-c <config file>, \-\-config <config file>
Supply a configuration file. The default is /etc/geni-chapi/chapi.ini
.TP
\-h, \-\-help
Show summary of options.
.SH EXAMPLES
.TP
List all identity providers and their respective member counts:
.B geni-list-idp-members
.SH AUTHOR
geni-list-idp-members was written by Raytheon BBN Technologies.
