#!/bin/sh

# Limits as of February 2, 2017
ERROR_LIMIT=2847
WARNING_LIMIT=46

RESULT=0
ERROR_COUNT=`python test/pep8.py --filename '*.py,*.py.in' --ignore W . | wc -l`
WARNING_COUNT=`python test/pep8.py --filename '*.py,*.py.in' --ignore E . | wc -l`

if test $ERROR_COUNT -gt $ERROR_LIMIT
then
        echo "Error count $ERROR_COUNT is greater than limit $ERROR_LIMIT"
        RESULT=1
fi

if test $WARNING_COUNT -gt $WARNING_LIMIT
then
        echo "Warning count $WARNING_COUNT is greater than limit $WARNING_LIMIT"
        RESULT=1
fi

# We could eventually watch for trailing whitespace in a similar fashion:
# find . -name .git -prune -o -type f -exec egrep -l " +$" {} \;

# We could add unit tests and invoke with something like:
# python -m unittest discover

exit $RESULT
