language: python
virtualenv:
  system_site_packages: true
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-m2crypto python-dateutil python-openssl
  - sudo apt-get install -y libxmlsec1 xmlsec1 libxmlsec1-openssl libxmlsec1-dev
  - sudo apt-get install -y python-sqlalchemy python-lxml python-psycopg2
before_script:
  - wget https://github.com/GENI-NSF/geni-tools/archive/v2.10.tar.gz -O /tmp/geni-tools.tar.gz
  - tar -xf /tmp/geni-tools.tar.gz -C /tmp
  - export PYTHONPATH=$PYTHONPATH:/tmp/geni-tools-2.10/src
  - test/setup_test_ch_server.sh
script:
  - test/travis-build
  - python -m unittest discover test
  - test/ch_server_tests.sh


