#!/bin/bash

# Exit on error
set -e
# Echo commands with variables expanded
set -x

# untar everything in the right place
sudo tar pxfz chapi.tgz -o -C /usr/share/geni-ch
GCFDIR=$(readlink /usr/share/geni-ch/portal/gcf)
sudo ln -s $GCFDIR /usr/share/geni-ch/gcf
sudo cp /usr/share/geni-ch/chapi/chapi/tools/.bashrc /usr/share/geni-ch/

# allow www-data to write to some AMsoil directories
sudo chown www-data.www-data /usr/share/geni-ch/chapi/AMsoil/deploy
sudo chown www-data.www-data /usr/share/geni-ch/chapi/AMsoil/log

sudo chmod 644 /etc/apache2/sites-available/ch-ssl
sudo patch --backup --ignore-whitespace -p0 /etc/apache2/sites-available/ch-ssl << EOF
--- /etc/apache2/sites-available/ch-ssl.orig    2013-10-08 11:18:46.447848440 -0400
+++ /etc/apache2/sites-available/ch-ssl 2013-11-14 12:31:03.722755485 -0500
@@ -182,14 +182,11 @@
        # MSIE 7 and newer should be able to use keepalive
        BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

-       # Include configuration files for clearinghouse services
-       Include /usr/share/geni-ch/sa/apache2.conf
-       Include /usr/share/geni-ch/ma/apache2.conf
-       Include /usr/share/geni-ch/pa/apache2.conf
-       Include /usr/share/geni-ch/sr/apache2.conf
-       Include /usr/share/geni-ch/cs/apache2.conf
-       Include /usr/share/geni-ch/logging/apache2.conf
-       Include /usr/share/xml-signer/etc/apache2.conf
+       SSLOptions +ExportCertData
+       SSLCACertificateFile /usr/share/geni-ch/CA/cacert.pem
+       SSLVerifyClient optional_no_ca
+       SSLVerifyDepth 3
+       Include /usr/share/geni-chapi/apache2.conf

 </VirtualHost>

EOF

sudo chmod +w /etc/geni-ch/settings.php
sudo sed -i 's/sr\/sr_controller.php/SR/g' /etc/geni-ch/settings.php

# At this point apache needs a restart, but that will get done
# by the invoking script (install_chapi)
#sudo service apache2 restart
