#!/bin/bash

# Exit on error
set -e
# Echo commands with variables expanded
set -x

if [ -z $1 ]
  then
    echo 'Need to supply a VM name'
    exit -1
fi

# Accept optional second arg to specify chapi branch
if [ -z $2 ]; then
  CHAPI_BRANCH=develop
else
  CHAPI_BRANCH=$2
fi

# install required modules
sudo apt-get update
sudo apt-get -y install libapache2-mod-fastcgi python-pip \
    python-dev python-flup libxslt-dev php5-xmlrpc
sudo apt-get -y --allow-unauthenticated install abac-0.1.6
sudo pip install flask==0.10.1 Flask-XML-RPC==0.1.2 blinker==1.3 \
    sqlalchemy==0.8.3 lxml==3.2.4

# clone chapi
echo "Checkout out chapi branch $CHAPI_BRANCH"
git clone trac.gpolab.bbn.com:/srv/git/chapi.git
cd chapi
git checkout "${CHAPI_BRANCH}"

# get gpo branch of local amsoil repo inside of chapi directory
git clone trac.gpolab.bbn.com:/srv/git/amsoil.git
mv amsoil AMsoil
cd AMsoil
git checkout gpo

# fix up the amsoil directory
for pl in chrm chapiv1rpc sarm marm csrm logging pgch
do
    ln -s ../../../chapi/plugins/$pl src/plugins/$pl
done
sudo chown www-data deploy log

# tar up chapi and then the whole package
cd ../..
tar cfpz chapi.tgz chapi
cp chapi/chapi/tools/install_ch .
tar cfp chapi_installer.tar chapi.tgz install_ch

chapi/chapi/tools/install_db ${1}
./install_ch
