#!/bin/bash

if [ -z $1 ]
  then
    echo 'Need to supply a VM name'
    exit -1
fi

cat > $HOME/.pgpass << EOF
localhost:*:portal:portal:portal
EOF
chmod 0600 $HOME/.pgpass

wget http://www.gpolab.bbn.com/~tmitchel/ch-db-export.sql
import_database.py --dump_file ch-db-export.sql --old_hostname ch.geni.net --new_hostname $1 --old_authority ch.geni.net --new_authority $1

psql -U portal -h localhost portal < update-1.sql
./migrate_assertions.sh
# uncomment next line if you want the pgeni3 aggregate in the db
# bin/add_pgeni3_am.sh

psql -U portal -h localhost portal << EOF
update service_registry set service_url = 'https://{$1}/secure/kmhome.php' where service_url = 'https://portal.geni.net/secure/kmhome.php';
update service_registry set service_type = service_type + 100 where service_type in (1, 2, 3, 5, 6, 9);
insert into service_registry (service_type, service_url, service_urn)
       values (1, 'https://${1}/SA', 'urn:publicid:IDN+${1}+authority+sa');
insert into service_registry (service_type, service_url, service_urn)
       values (2, 'https://${1}/SA', 'urn:publicid:IDN+${1}+authority+sa');
insert into service_registry (service_type, service_url, service_urn)
       values (3, 'https://${1}/MA', 'urn:publicid:IDN+${1}+authority+ma');
insert into service_registry (service_type, service_url)
       values (5, 'https://${1}/LOG');
insert into service_registry (service_type, service_url)
       values (6, 'https://${1}/CS');
insert into service_registry (service_type, service_url)
       values (9, 'https://${1}/PGCH');
\q
EOF
