#!/bin/bash

if [ -z $1 ]
  then
    echo 'Need to supply a VM name'
    exit -1
fi

# Exit on error
set -e
# Echo commands with variables expanded
set -x

# get the update-1.sql file and certs from the proto-ch tree
git clone git+ssh://trac.gpolab.bbn.com/srv/git/proto-ch.git
cd proto-ch
#git checkout sliverinfo
git checkout chapidev
cp sa/db/postgresql/update-1.sql ..
cp bin/migrate_assertions.sh ..
cd ..

# clone chapi
git clone git+ssh://trac.gpolab.bbn.com/srv/git/chapi.git

cd chapi
git checkout develop
# get gpo branch of local amsoil repo inside of chapi directory
git clone git+ssh://trac.gpolab.bbn.com/srv/git/amsoil.git
mv amsoil AMsoil
cd AMsoil
git checkout gpo

# fix up the amsoil directory
for pl in chrm chapiv1rpc sarm marm csrm logging pgch
do
    ln -s ../../../chapi/plugins/$pl src/plugins/$pl
done
sudo chown www-data deploy log

# tar up chapi and then the whole package
cd ../..
tar cfpz chapi.tgz chapi
cp chapi/chapi/tools/install_ch .
cp chapi/chapi/tools/install_db .
tar cfp chapi_installer.tar chapi.tgz install_ch install_db update-1.sql migrate_assertions.sh

./install_db ${1}
./install_ch
