#!/bin/bash

echoerr() { echo "$@" 1>&2; }

# Exit on error
set -e
# Echo commands with variables expanded
set -x

if [ -z $1 ]; then
  echoerr 'Need to supply a VM name'
  exit 1
fi

# install required modules
sudo apt-get update
sudo apt-get -y install libapache2-mod-fastcgi python-pip \
    python-dev python-flup libxslt-dev php5-xmlrpc
sudo apt-get -y --allow-unauthenticated install abac-0.1.6
sudo pip install flask==0.10.1 Flask-XML-RPC==0.1.2 blinker==1.3 \
    sqlalchemy==0.8.3 lxml==3.2.4

TMP_DIR=/tmp/chapi-install
if [ -x "${TMP_DIR}" ]; then
  echoerr "Temporary build directory '${TMP_DIR}' exists."
  echoerr "Please remove it and run this script again."
  exit 1
fi

# Find out where this script lives. It should be in the
# "tools" directory of a chapi tree.
TOOLS_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CHAPI_DIR="${TOOLS_DIR}"/../../chapi

mkdir "${TMP_DIR}"
cd "${TMP_DIR}"
mkdir chapi
cp -r "${CHAPI_DIR}" chapi
# Clean up any git cruft that got copied
find chapi -name '.git*' -delete
cd chapi

# Get GPO version of AMsoil from local web site
AMSOIL_VERSION=AMsoil-gpo-0.3.2
AMSOIL_FILE=${AMSOIL_VERSION}.tar.gz
wget http://www.gpolab.bbn.com/internal/projects/chapi/${AMSOIL_FILE}
tar zxf "${AMSOIL_FILE}"
ln -s "${AMSOIL_VERSION}" AMsoil
cd AMsoil

# fix up the amsoil directory
for pl in chrm chapiv1rpc sarm marm csrm logging pgch
do
    ln -s ../../../chapi/plugins/$pl src/plugins/$pl
done
sudo chown www-data deploy log

# tar up chapi and then the whole package
cd ../..
tar cfpz chapi.tgz chapi
cp chapi/chapi/tools/install_ch .
tar cfp chapi_installer.tar chapi.tgz install_ch

chapi/chapi/tools/install_db ${1}
./install_ch

# Clean up the temp directory
sudo rm -rf "${TMP_DIR}"

cd "${CHAPI_DIR}"
autoreconf --install
./configure --prefix=/usr --sysconfdir=/etc --bindir=/usr/local/bin --sbindir=/usr/local/sbin
make
sudo make install
sudo service apache2 restart
