#!/bin/bash

if [ -z $1 ]
  then
    echo 'Need to supply a VM name'
    exit -1
fi

# Exit on error
set -e
# Echo commands with variables expanded
set -x

# untar everything in the right place
tar pxfz chapi.tgz -C /usr/share/geni-ch
#tar pxfz gcf.tar.gz -C /usr/share/geni-ch
GCFDIR=$(readlink /usr/share/geni-ch/portal/gcf)
ln -s $GCFDIR /usr/share/geni-ch/gcf
tar xfz abac.tar.gz -C /usr/share/geni-ch
#mv /usr/share/geni-ch/gcf-2.3.3 /usr/share/geni-ch/gcf
mv /usr/share/geni-ch/abac-0.1.5 /usr/share/geni-ch/abac
#cp /usr/share/geni-ch/chapi/proto-ch/lib/php/*.php /usr/share/geni-ch/lib/php
#cp sr/certs/* /usr/share/geni-ch/sr/certs/
#cp portal/* /var/www/secure/
cp /usr/share/geni-ch/chapi/chapi/tools/.bashrc /usr/share/geni-ch/

# patch the authority parameter
sed -i "s/ch-mt.gpolab.bbn.com/${1}/g" /usr/share/geni-ch/chapi/chapi/plugins/chapiv1rpc/chapi/Parameters.py

# install required modules
apt-get update
apt-get -y install libapache2-mod-fastcgi python-setuptools \
    python-dev python-openssl python-flup nginx libxslt-dev \
    autoconf-archive g++ swig php5-xmlrpc
easy_install flask Flask-XML-RPC blinker pika sqlalchemy lxml

# build abac
cd /usr/share/geni-ch/abac/
./configure --prefix=/usr
make
make install

# patch the apache configuration files
patch --backup -p0 /etc/apache2/mods-available/fastcgi.conf << EOF
--- fastcgi.conf	2013-09-03 15:51:58.606431660 -0400
+++ /etc/apache2/mods-available/fastcgi.conf	2013-09-06 08:46:20.682426270 -0400
@@ -2,4 +2,5 @@
   AddHandler fastcgi-script .fcgi
   #FastCgiWrapper /usr/lib/apache2/suexec
   FastCgiIpcDir /var/lib/apache2/fastcgi
+  FastCgiServer /usr/share/geni-ch/chapi/AMsoil/src/main.py -port 9003 -initial-env PYTHONPATH=/usr/share/geni-ch/chapi/chapi:/usr/share/geni-ch/chapi/chapi/tools:/usr/share/geni-ch/gcf/src -initial-env GCFHOME=/usr/share/geni-ch/gcf/src -initial-env CHAPIHOME=/usr/share/geni-ch/chapi/chapi
 </IfModule>
EOF

patch --backup -p0 /etc/apache2/mods-available/deflate.conf << EOF
--- /etc/apache2/mods-enabled/deflate.conf	2013-07-12 09:39:20.000000000 -0400
+++ chapi/deflate.conf	2013-09-03 16:12:34.894429239 -0400
@@ -1,6 +1,7 @@
 <IfModule mod_deflate.c>
           # these are known to be safe with MSIE 6
-          AddOutputFilterByType DEFLATE text/html text/plain text/xml
+#          AddOutputFilterByType DEFLATE text/html text/plain text/xml
+          AddOutputFilterByType DEFLATE text/plain
 
           # everything else may cause problems with MSIE 6
           AddOutputFilterByType DEFLATE text/css
EOF

chmod 644 /etc/apache2/sites-available/ch-ssl
patch --backup -p0 /etc/apache2/sites-available/ch-ssl << EOF
--- ch-ssl	2013-09-06 08:54:59.234460479 -0400
+++ /etc/apache2/sites-available/ch-ssl	2013-09-06 08:46:59.526437589 -0400
@@ -190,6 +190,18 @@
 	Include /usr/share/geni-ch/cs/apache2.conf
 	Include /usr/share/geni-ch/logging/apache2.conf
 
+        SSLOptions +ExportCertData
+        SSLCACertificateFile /usr/share/geni-ch/CA/cacert.pem
+        SSLVerifyClient optional_no_ca
+        SSLVerifyDepth 3
+        ScriptAlias /SA /usr/share/geni-ch/chapi/AMsoil/src/main.py
+        ScriptAlias /MA /usr/share/geni-ch/chapi/AMsoil/src/main.py 
+        ScriptAlias /CS /usr/share/geni-ch/chapi/AMsoil/src/main.py 
+        ScriptAlias /CH /usr/share/geni-ch/chapi/AMsoil/src/main.py 
+        ScriptAlias /LOG /usr/share/geni-ch/chapi/AMsoil/src/main.py 
+        ScriptAlias /PGCH /usr/share/geni-ch/chapi/AMsoil/src/main.py 
+        ScriptAlias /SR /usr/share/geni-ch/chapi/AMsoil/src/main.py 
+
 </VirtualHost>
 
 # Catch-all default virtual host, so other CNAMEs to this IP are not
EOF

chmod +w /etc/geni-ch/settings.php
sed -i 's/sr\/sr_controller.php/SR/g' /etc/geni-ch/settings.php

# restart apache
service apache2 restart
