#!/bin/bash

# Exit on error
set -e
# Echo commands with variables expanded
set -x

# download abac and gcf
wget --output-document abac.tar.gz http://abac.deterlab.net/src/abac-0.1.5.tar.gz
wget --output-document gcf.tar.gz --post-data "software=gcf-2.3.3.tar.gz&accept=I+have+read+and+accept+the+GPO+terms+of+service+and+disclaimer" http://software.geni.net/local-sw/real_download

# clone chapi
git clone git+ssh://trac.gpolab.bbn.com/srv/git/chapi.git

# get gpo branch of local amsoil repo inside of chapi directory
cd chapi
#git clone git+ssh://trac.gpolab.bbn.com/srv/git/amsoil.git
git clone git+ssh://trac.gpolab.bbn.com/home/dmontana/AMsoil
cd AMsoil
git checkout gpo

# fix up the amsoil directory
for pl in chrm chapiv1rpc sarm marm csrm logging pgch
do
    ln -s ../../../chapi/plugins/$pl src/plugins/$pl
done
chmod 777 deploy log

# tar up chapi and then the whole package
cd ../..
tar cfpz chapi.tgz chapi
cp chapi/chapi/tools/install_ch .
tar cfp chapi_installer.tar abac.tar.gz chapi.tgz gcf.tar.gz install_ch
